// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Infected struct {
	UserIDReported uuid.UUID
	UserIDNotified uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Inventory struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type InventoryItem struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	ItemID      uuid.UUID
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Item struct {
	ID          uuid.UUID
	Description string
	Score       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                        uuid.UUID     `json:"id"`
	Name                      string        `json:"name"`
	Age                       int32         `json:"age"`
	Gender                    string        `json:"gender"`
	Latitude                  string        `json:"latitude"`
	Longitude                 string        `json:"longitude"`
	Infected                  sql.NullBool  `json:"infected"`
	ContaminationNotification sql.NullInt32 `json:"contamination_notification"`
	CreatedAt                 time.Time     `json:"created_at"`
	UpdatedAt                 time.Time     `json:"updated_at"`
}
